### ISSUE TITLE
Wards killed without killer

### ISSUE THREAD

**Issue by evaldobratti** [odota/parser#27]
I was checking if #26 was working as intended and still found some wards that did not live their whole life without a proper killer.
After analysing some replays we have still have 2 problems:

- [4204756967](https://www.opendota.com/matches/4204756967/vision) a lot of wards die at 27:33, that is the ending of the match, should we show something different in this case?
- [4203845546](https://www.opendota.com/matches/4203845546/vision) some wards were killed by the creeps (mirana sentry@24:42, aa observer@25:49). I think showing a creep icon would be nice here.

**Comment by howardchung** [comment]
Wards killed by creeps:
Looks like the API already returns a string for creeps, so this should just be an update on the odota/web side:
`"attackername": "npc_dota_creep_badguys_ranged_upgraded_mega",`

End of match:
I think this is fine to leave as is. End of match also means end of ward lifetime
