### ISSUE TITLE
Question about Quickstart

### ISSUE THREAD

**Issue by wx930910** [odota/parser#31]
I tried to run Main.java and then post the .dem file via cmd and got the error message says that
![image](https://user-images.githubusercontent.com/22060531/67577994-8df93380-f70f-11e9-99c3-8451890c60d9.png)

Then I tried to use docker run the parser and post .dem file via cmd but got an error message (I am a beginner to docker):
![image](https://user-images.githubusercontent.com/22060531/67578155-e3cddb80-f70f-11e9-848f-68cee50a1999.png)

Could you please tell me how should I run the parser correctly? Thanks for any help you can provide!

**Comment by howardchung** [comment]
For the Docker issue you likely need to run with --net=host to make it use your host network stack, or open a port to the container with port forwarding. There should be documentation on the Docker site.
