### ISSUE TITLE
Extract player's Dota Plus hero level

### ISSUE THREAD

**Issue by builder-247** [odota/parser#34]
It's stored in [CPlayerLocalDota](https://github.com/ButterflyStats/butterfly/blob/master/src/butterfly/private/flattened_serializer.inline#L113), I've spent a few hours now trying to add it myself but my unfamiliarity with clarity (and java) has made the task rather hard.

So I'd appreciate if someone could point me to the right direction or even add it themselves.

**Comment by howardchung** [comment]
Is that an entity or some other special data structure?

You can try finding it in https://github.com/spheenik/clarity-analyzer

**Comment by builder-247** [comment]
After asking for some help from the guys at STRATZ I got it figured out. PR coming later.
