### ISSUE TITLE
Meaning of actions

### ISSUE THREAD

**Issue by daQiuQiu** [odota/parser#4]
Hi,
I recently study data 2 parser.
I tried your parser and I got some output, is there any documentation for meanings?
eg.
{"time":285,"type":"actions","key":"1","slot":0}
whats key:1 means?
and gold_reason, xp_reason?
@howardchung 
Thank you very much!

**Comment by howardchung** [comment]
It's the order type:
https://github.com/SteamDatabase/GameTracking/blob/b24b081a8383e636bd954ca7cd34df5211154851/Protobufs/dota/dota_commonmessages.proto#L102

I made a list of some of the gold reasons here:
https://github.com/odota/dotaconstants/blob/master/json/gold_reasons.json
