### ISSUE TITLE
Metadata available for the parsed data json?

### ISSUE THREAD

**Issue by nevinbaiju** [odota/parser#40]
Hi, is there a metadata available for the parsed data.

There are a lot of variables describes who's meaning is difficult to interpret. So is there any documentation available like that?

Example "type":"interval", from what I have derived it is just logging the status as time progresses i.e increment in gold, etc. However some others are very difficult to interpret.

**Comment by howardchung** [comment]
https://docs.opendota.com is the general reference.

**Comment by nevinbaiju** [comment]
Yes I had referred that, however it only contains the docs of the api usage right? I was wondering if there is a doc of the schema of the replay file itself.

**Comment by howardchung** [comment]
You'll have to use something like https://github.com/spheenik/clarity-analyzer to check the file contents

**Comment by nevinbaiju** [comment]
Analytics is fine, I just want to understand the meaning of the variables, so I'll be able to write analytics packages and stuff.

**Comment by howardchung** [comment]
Unfortunately there's no documentation on the details of the replay file, you'll have to figure it out based on the name of the various entity properties

**Comment by nevinbaiju** [comment]
Okay, thanks!

**Comment by baozidai** [comment]
@nevinbaiju 
I got the same question. 
I am thinking if it's ok to make a repository to record the explanations of the variables ? 
Or just make PR to this repo https://github.com/odota/dotaconstants
