### ISSUE TITLE
AbilityList: For loop ends 1 too early

### ISSUE THREAD

**Issue by steakscience** [odota/parser#48]
Here, it should be 32 instead of 31

https://github.com/odota/parser/blob/3b1aa7215c725551106f51d5338f002c0c74ed77/src/main/java/opendota/Parse.java#L768-L777

This is because there are abilities at 31. Looping with `i < 31` will skip over the last ability

https://github.com/odota/parser/blob/3b1aa7215c725551106f51d5338f002c0c74ed77/src/main/java/opendota/Parse.java#L822-L826

**Comment by howardchung** [comment]
So the properties actually range from 0-32 (33 values?)

**Comment by tiso7** [comment]
The properties range from 0000 to 0031, so 0 to 31. However, in the for loop, it only goes from 0 to 30 because of the condition `i < 31`. I believe that should be `i < 32` instead. So same for `ArrayList<>(31)`, that should be `ArrayList<>(32)`.

**Comment by howardchung** [comment]
Ah I see. Happy to take a PR to fix this!
